server:
  host: localhost
  port: 33333
  idle_timeout: 30m
  log_level: DEBUG
terminal:
  word_wrap_min: 80
password:
  min_length: 6
  max_length: 72
  bcrypt_cost: 10
data:
  area_path: _data/areas