server:
  host: localhost
  port: 33333
  idle_timeout: 30m
  log_level: DEBUG
terminal:
  word_wrap_min: 80
password:
  min_length: 6
  max_length: 72
  bcrypt_cost: 10
data:
  accounts_path: _data/accounts
  areas_path: _data/areas
  players_path: _data/players
  items_file: items.yml
  manifest_file: manifest.yml
  npcs_file: npcs.yml
  quests_file: quests.yml
  rooms_file: rooms.yml